codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: yes
