codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 4

coverage:
  status:
    patch: no
    changes: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: yes
